document.writeln("<div id='helpCenter'>");
document.writeln("	<div>");
document.writeln("		<ul>");
document.writeln("			<li><a href='' target='_blank'><b>新手上路</b></a></li>");
document.writeln("			<li><a href='' target='_blank'>购物流程</a></li>");
document.writeln("			<li><a href='' target='_blank'>会员注册</a></li>");
document.writeln("			<li><a href='' target='_blank'>常见问题</a></li>");
document.writeln("			<li><a href='' target='_blank'>订单状态</a></li>");
document.writeln("		</ul>");
document.writeln("		<ul class='line'>");
document.writeln("			<li><a href=''><b>关于支付</b></a></li>");
document.writeln("			<li><a href='' target='_blank'>货到付款</a></li>");
document.writeln("			<li><a href='' target='_blank'>银行汇款</a></li>");
document.writeln("			<li><a href='' target='_blank'>招商银行分期付款</a></li>");
document.writeln("			<li><a href='' target='_blank'>支付宝在线支付</a></li>");
document.writeln("		</ul>");
document.writeln("		<ul class='line'>");
document.writeln("			<li><a href=''><b>配送说明</b></a></li>");
document.writeln("			<li><a href='' target='_blank'>配送费用</a></li>");
document.writeln("			<li><a href='' target='_blank'>配送时效</a></li>");
document.writeln("			<li><a href='' target='_blank'>物流快递</a></li>");
document.writeln("			<li></li>");
document.writeln("		</ul>");
document.writeln("		<ul class='line'>");
document.writeln("			<li><a href=''><b>售后服务</b></a></li>");
document.writeln("			<li><a href='' target='_blank'>售后服务政策</a></li>");
document.writeln("			<li><a href='' target='_blank'>如何换货</a></li>");
document.writeln("			<li><a href='' target='_blank'>如何退货</a></li>");
//document.writeln("			<li><a href='/helpdetail.aspx?helpid=54' target='_blank'>30天退换货</a></li>");
document.writeln("		</ul>");
document.writeln("		<ul class='line'>");
document.writeln("			<li><a href=''><b>会员中心</b></a></li>");
document.writeln("			<li><a href='' target='_blank'>会员等级</a></li>");
document.writeln("			<li><a href='' target='_blank'>如何成为贵宾会员</a></li>");
document.writeln("			<li><a href='' target='_blank'>会员优惠</a></li>");
document.writeln("			<li><a href='' target='_blank'>积分制度</a></li>");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("<div id='bottom'>");
document.writeln("	<ul>");
document.writeln("		<li><a href=''>手机官网</a></li>");
document.writeln("		<li class='line'></li>");
document.writeln("		<li><a href=''>商城介绍</a></li>");
document.writeln("		<li class='line'></li>");
document.writeln("		<li><a href=''>联系我们</a></li>");
document.writeln("		<li class='line'></li>");
document.writeln("		<li><a href=''>隐私权声明条款</a></li>");
document.writeln("		<li class='line'></li>");
document.writeln("		<li><a href=''>友情链接</a></li>");
document.writeln("	</ul>");
document.writeln("</div>");